### ISSUE TITLE
Update to latest web3j version

### ISSUE THREAD

**Issue by marodev** [web3j/homebrew-web3j#10]
Hello,

are you planning to update the formula to the latest web3j version (4.8.1) ?

**Comment by xaviarias** [comment]
Hi, yes sure we will. Thanks for raising it!

**Comment by marodev** [comment]
Hi Xavi,

Glad to hear! Is there a timeline for when you are going to address this?

**Comment by xaviarias** [comment]
Hi, for now the only CLI we maintain is the [Epirus CLI](https://github.com/epirus-io/epirus-cli). It has the same functionality to the Web3j CLI.

I'm closing this issue now but we might revert to the Web3j CLI in the near future.
